export const cuisineList = [
    "Northern",
    "home food",
    "Western",
    "South Indian",
    "Eastern Indian", 
    "North-east Indian",
    "Indianised",
    "Americans",
    "BBQ",
    "Breakfast",
    "Burgers",
    "Chinese",
    "Dinner",
    "Lunch",
    "Healthy",
    "Italian",
    "Japanese",
    "Mexican",
];